CREATE TABLE RequestsLCD (
   RequestLCDID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
   UserID INT NOT NULL,
   lcdID INT NOT NULL,
   RequestDate DATETIME NOT NULL,
   StartDate DATETIME NOT NULL,
   EndDate DATETIME NOT NULL,
   Status VARCHAR(250) NOT NULL,
   FOREIGN KEY (UserID) REFERENCES UserTable(userID),
   FOREIGN KEY (lcdID) REFERENCES LCDTable(LCDID)
);